### ISSUE TITLE
C# 8.0 already does this

### ISSUE THREAD

**Issue by ATypescriptEnjoyer** [mrstebo/FluentSwitch#1]
Exchuseeee me! 

C# 8.0 does this

lookie here: https://blogs.msdn.microsoft.com/dotnet/2018/11/12/building-c-8-0/

Nice try

Kind Regards,
Me

**Comment by mrstebo** [comment]
Thanks @JackRyder, this is for projects that are using earlier version of C# :stuck_out_tongue_winking_eye:
